name: Generate Contribution Snake  

on:  
  schedule:  
    - cron: "0 0 * * *"  # Runs daily at midnight UTC  
  workflow_dispatch:  

jobs:  
  generate:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: write  
      
    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Generate Contribution Snake  
        uses: Platane/snk@v3  
        with:  
          github_user_name: ayusharyaneth  # Replace with your GitHub username  
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark  

      - name: Ensure Correct File Permissions  
        run: chmod -R 777 .  

      - name: Create Output Directory  
        run: mkdir -p output  

      - name: Move Generated Files  
        run: |  
          mv github-snake.svg output/github-snake.svg  
          mv github-snake-dark.svg output/github-snake-dark.svg  

      - name: Commit and Push to the Output Branch  
        run: |  
          git config --global user.email "github-actions@github.com"  
          git config --global user.name "github-actions"  
          git add output/github-snake.svg output/github-snake-dark.svg  
          git commit -m "🐍 Updated Contribution Snake" || echo "No changes to commit"  
          git push origin main
